language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: "3.7"
      dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
  allow_failures:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip install flake8      
before_script:
  # fail the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings. The GitHub web ui editor is 127 chars wide
  - SELECT=C,E10,E11,E401,E502,E703,E8,E9,F,W191,W291,W292,W293,W391
  - flake8 . --count --exit-zero --select=${SELECT} --max-complexity=10 --max-line-length=127 --statistics
script: true  # more tests go here...
