"""Subclass of MainFrameBase, which is generated by wxFormBuilder."""

import wx
import gui

# Implementing MainFrameBase
class ValueEditDialog ( gui.EditDialogBase ):
	def __init__( self, parent ):
		gui.EditDialogBase.__init__( self, parent )
		
	# Handlers forevents.

	def m_FinishEdit( self, event ):
                print("Finish editing")
		gui.EditDialogBase.EndModal(self, 0)
		event.Skip()

	


