# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.provision "shell", inline: <<-SHELL
        apt-get -y update
        echo "[MAVPROXY]: Installing pip ..."
        apt-get -y install python-pip
        easy_install -U pip
        echo "[MAVPROXY]: Installing Sphinx ... "
        pip install sphinx
        cd /vagrant
        make html
    SHELL
end
